name: Pri.Messaging CI Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "CI Build"
    runs-on: ubuntu-latest

    steps:
    - name: Clone source
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET 6.0
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: |
        dotnet test --no-restore --no-build --filter Category!=Integration --verbosity normal --configuration Release
